pipeline {
    agent any 
    // Environment Variables
    environment {
            NAME ='bix'
            LASTNAME = 'dudu'
            
            //using credentials
            secret = credentials('TEST')
            // TEST is the name of the credentials
        }   
    
    stages {
        stage('Building'){
            steps {
                sh 'echo "Building stage" ' 
                sh '''
                    echo "By the way, I can do more stuff in here"
                    ls -lah
                '''
            }
        }
        
        stage('Testing'){
            steps{
                echo 'Testing stage'
                // will run the file three times based on retry(3)  
            }
        }

        stage('Timeout'){
            steps{
                retry(3){
                    echo 'Time out stage'
                    // will run the file three times based on retry(3)
                }

                timeout(time:3,unit: 'SECONDS'){
                    sh 'sleep 5'
                }
                // this will make the task to timeout after three seconds
            }
        }

        
        stage('Print Environment'){
            steps {
                sh 'echo $NAME $LASTNAME'
            }
        }
        
        stage('Deploying'){
            steps {
                echo 'Deploying'
                sh 'echo $secret'
            }
        }
    }

    //Post Actions
    post{
        // 1. Always -> will always get executed
        always {
            echo 'I will always get executed'
        }
        // 2. success -> only get executed  if the pipeline is a success
        success {
            echo 'I will be executed on success'
        }
        // 3. failure -> will only get executed when there is failure
        failure {
            echo 'I will be executed on failure'
        }
        // 4. unstable -> will get executed if there is instability 
        unstable {
            echo 'I will be executed when there is instability'
        }
    }
}

// This is a simple jenkins pipeline